name: Website

on:
  pull_request:
    paths:
      - website/**
      - .github/workflows/website.yml
  push:
    branches-ignore:
      - dependabot/**
    paths:
      - website/**
      - .github/workflows/website.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: website/package-lock.json

      - name: 📥 Download deps
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Setup EnhanceDocs CLI
        uses: enhancedocs/enhancedocs-github-action@0.1.0
        with:
          api-key: ${{ secrets.ENHANCEDOCS_API_KEY }}

      - name: Build EnhanceDocs
        run: enhancedocs build ../docs

      - name: Push to EnhanceDocs
        run: enhancedocs push <replace_with_project_id>
